language: node_js

node_js:
  - 'stable'
  - '6'

sudo: false

env:
  - workerCount=3

matrix:
  fast_finish: true

branches:
  only:
  - master

before_script:
  - npm i -g typescript
  - npm i -g ts-node
  - npm i -g jasmine-ts
  - npm i -g

install:
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1
